### PR TITLE
Generic ReadReg

### PR DESCRIPTION
**Pull request by abbeman**
Could be nice, e.g. when reading the acceleration vector? This:

        uint8_t data[6];

        this->m_i2c->ReadReg(OUT_X_L | MULTI_BYTE_READ_ADDR, data, 6);

        vector.X  = data[0] << 0;
        vector.X |= data[1] << 8;
        vector.Y  = data[2] << 0;
        vector.Y |= data[3] << 8;
        vector.Z  = data[4] << 0;
        vector.Z |= data[5] << 8;

turns into this:

        uint16_t data[3];

        this->m_i2c->ReadReg(OUT_X_L | MULTI_BYTE_READ_ADDR, data, 3);

        vector.X  = data[0];
        vector.Y  = data[1];
        vector.Z  = data[2];

### CODE REVIEW

**Comment by abbeman** [comment]
Now, since I can't test on hardware at the moment I have set up some tests on x86 and AFAICT I get identical results to the original code.

**Review by LHelge — APPROVED** [review]
Great idéa

**Comment by LHelge** [comment]
Seems to work, see commit
https://github.com/LHelge/BCD-watch/pull/9/commits/6210a376adc298b7f7b53274658634fd56bd1d66

**Comment by abbeman** [comment]
Nice

**Pull request merged**
